### ISSUE TITLE
Performance is bad and scales badly

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/llvm-pretty-bc-parser#129] opened 2019-05-09 23:05 UTC
See https://github.com/GaloisInc/crucible/issues/227

Basically, realistically-sized bitcode files seem to cause major problems for the bitcode parser.  Most likely the culprit is poor algorithmic choices and/or space leaks.

Some time with a profiler and some TLC on the performance front seems warranted.

**Comment by brianhuffman** [comment] 2019-05-13 16:53
Heap profiling shows that a couple of different phases of execution have space leaks. Both are parts of function `finalizeModule` in `Data.LLVM.BitCode.IR.Module`.

First, calls to `finalizePartialUnnamedMd` cause ever-increasing numbers of pair constructors and `stg_sel_upd` closures (representing tuple projections) to be allocated. These apparently arise from `MonadLib`'s state monad transformer. State-related operations are not used in `finalizePartialUnnamedMd`.

Second, calls to `finalizePartialDefine` cause an ever-increasing number of function closures to be allocated, perhaps having to do with the reader monad transformer.

**Comment by brianhuffman** [comment] 2019-05-13 19:49
Switching from the `MonadLib` package to `mtl` makes the space leaks go away, and yields a modest speedup. This is an easy change that I would recommend.

Some other changes I could recommend:

* Make a variant of the `Parse` monad that does not use `StateT`, and use it wherever possible (including nearly all of the `finalize` functions)
* Switch from `Data.Map` to `Data.IntMap` wherever possible

**Comment by brianhuffman** [comment] 2019-05-14 00:02
The changes I suggested are implemented in pull request #130. However, the problem is far from being satisfactorily fixed: GC still takes about half of the total runtime.

Switching from `monadLib` to `mtl` did not make *all* of the space leaks go away: Heap profiling now shows a large number of "PAP" heap nodes (i.e. partial applications) being created when `finalizePartialDefine` is being run. Profiling with `-hb` and `-hy -hbdrag` shows that these "PAP" nodes exist in the "drag" state, where they are used at least once, but then not garbage collected until significantly after their last use.

It seems that an awful lot of stuff of type `BitString` is being allocated, but it seems that it is mostly used later. Reducing the memory footprint of this will require some major algorithmic changes, I think.

**Comment by brianhuffman** [comment] 2019-05-14 00:09
Further heap profiling with `-hm` shows that nearly all of the extra memory usage in the `finalizePartialDefine` phase is due to functions in module `Text.LLVM.Labels`.

**Comment by robdockins** [comment] 2019-05-14 00:14
Those functions do the actual traversal of statements and instructions, etc to adjust all the labels.  The partial applications might be the recursive calls to `relabel f`.

The easiest way to squash this space leak might be just to add strictness annotations to all the subterms of the `Instr'`, `Stmt'` datatypes, etc.  It's also using GHC.Generics to generically traverse other datatypes.   As I recall, Data.Generics isn't exactly high performance

**Comment by brianhuffman** [comment] 2019-05-14 04:47
In `Text.LLVM.Labels`, there is a class `HasLabel` (providing the `relabel` method) where most of the instances are defined using `GHC.Generics`. After redefining a four `HasLabel` instances manually, the execution time is 15% faster, and "total memory in use" (as shown by `+RTS -s`) is down about 40%.

I'm sure it would help to convert *all* the `HasLabel` instances in the same way, but there are about 16 more datatypes to do, and things are already quite verbose. We should probably use Template Haskell to generate the instance definitions; I could use some assistance from a TH expert with that.

**Comment by robdockins** [comment] 2019-05-14 17:27
Yikes! That's a pretty intense difference.  I suppose those instances are literally doing nothing except traversing the substructure, right?

**Comment by robdockins** [comment] 2019-05-14 17:44
@glguy, it looks like you added the generic relabeling code awhile back.  Do you know any good tricks to squash space leaks in generics code like this without having to rewrite it?

**Comment by glguy** [comment] 2019-05-14 19:31
@brianhuffman and I worked on https://github.com/elliottt/llvm-pretty/tree/th-generated-relabel today and Brian's going to keep working on it and make a PR

**Comment by kquick** [comment] 2019-07-21 18:08
@brianhuffman With the above changes merged, should this issue be closed or is there further investigation needed?

**Comment by robdockins** [comment] 2019-07-23 18:11
My understanding is that we will need to implement pretty major API changes if we want to improve performance in a significant way.  In particular, we will probably want to move to an on-demand parsing API, where AST nodes for functions, etc. are only generated when asked for.

So, we should either close this ticket and open a new one for refactoring the API or rebrand this ticket.

**Comment by siddharthist** [comment] 2019-07-23 20:37
That seems separate enough that it would warrant its own discussion.

**Closed by siddharthist** 2019-07-23 20:37 UTC
