### ISSUE TITLE
`CMPXCHG` is unimplemented

### ISSUE THREAD

**Issue by TomMD** [GaloisInc/llvm-pretty-bc-parser#56] opened 2017-06-21 06:24 UTC
When dealing with disassembly and re-assembly of foundation_lib's hashtable.c file I see:

```
Error
  { errContext =
      [ "FUNC_CODE_CMPXCHG"
      , "hashtable32_set"
      , "FUNCTION_BLOCK"
      , "MODULE_BLOCK"
      , "Bitstream"
      ]
  , errMessage = "not implemented"
  }
```

**Comment by siddharthist** [comment] 2019-01-11 19:57
Duplicate of #18

**Closed by siddharthist** 2019-01-11 19:57 UTC
